// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"go-skeleton/app/http/controllers"
	"go-skeleton/app/http/controllers/interfaces"
	"go-skeleton/app/repositories"
	"go-skeleton/app/services"
)

// Injectors from wire.go:

// Add new interfaces to return value as needed
func InitializeControllers() (interfaces.HealthController, error) {
	healthRepository := repositories.NewHealthRepository()
	healthService := services.NewHealthService(healthRepository)
	healthController := controllers.NewHealthController(healthService)
	return healthController, nil
}

// wire.go:

var healthSet = wire.NewSet(repositories.NewHealthRepository, services.NewHealthService, controllers.NewHealthController)
