// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-skeleton/app/http/controllers"
	"go-skeleton/app/http/controllers/interfaces"
	"go-skeleton/app/repositories"
	"go-skeleton/app/services"
)

// Injectors from wire.go:

// InitializeControllers initializes all controllers with their dependencies
func InitializeControllers() (interfaces.HealthController, error) {
	healthRepository := repositories.NewHealthRepository()
	healthService := services.NewHealthService(healthRepository)
	healthController := controllers.NewHealthController(healthService)
	return healthController, nil
}
